import React, { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import Layout from '../components/Layout';
import { api } from '../services/api';
import type { AptitudeResultData, PerformanceItem } from '../aptitudeTypes';

const Performance: React.FC<{ title: string; items: PerformanceItem[] }> = ({ title, items }) => <section className="bg-white dark:bg-neutral-900 border border-slate-100 dark:border-neutral-800 rounded-3xl p-6"><h2 className="text-lg font-black mb-5 text-slate-900 dark:text-neutral-100">{title}</h2><div className="space-y-4">{items.map((item) => <div key={item.name}><div className="flex justify-between text-sm font-bold mb-2"><span className="text-slate-700 dark:text-neutral-200">{item.name}</span><span className="text-blue-600">{item.accuracy}%</span></div><div className="h-2 bg-slate-100 dark:bg-neutral-800 rounded-full overflow-hidden"><div className="h-full bg-blue-600 rounded-full" style={{ width: `${item.accuracy}%` }} /></div><p className="text-[10px] text-slate-400 mt-1">{item.correct}/{item.total} correct</p></div>)}</div></section>;

const AptitudeResult: React.FC = () => {
  const { testId } = useParams();
  const [data, setData] = useState<AptitudeResultData | null>(null);
  const [error, setError] = useState('');
  useEffect(() => { api.get<AptitudeResultData>(`/aptitude/tests/${testId}/result`).then(setData).catch((e) => setError(e.message)); }, [testId]);
  if (!data) return <Layout><main className="max-w-xl mx-auto px-4 py-20 text-center font-bold text-slate-500">{error || 'Loading result…'}</main></Layout>;
  return <Layout><main className="max-w-7xl mx-auto px-4 sm:px-6 py-10">
    <div className="bg-slate-950 dark:bg-blue-950 text-white rounded-[2.5rem] p-8 sm:p-10 mb-7 flex flex-col md:flex-row md:items-center justify-between gap-7">
      <div><span className="text-[10px] font-black uppercase tracking-[0.25em] text-blue-300">Test complete</span><h1 className="text-3xl sm:text-4xl font-black mt-3">{data.test.title}</h1><p className="text-slate-300 mt-2">{data.test.section} · {data.test.difficulty} · {data.test.company}</p></div>
      <div className="text-center bg-white rounded-3xl border border-slate-200 px-10 py-6 text-slate-900 dark:bg-neutral-900 dark:border-white/10 dark:text-neutral-100"><div className="text-5xl font-black">{data.score}%</div><div className="text-xs uppercase tracking-widest font-black text-blue-600 dark:text-blue-300 mt-2">Score</div></div>
    </div>
    <div className="grid grid-cols-2 lg:grid-cols-5 gap-3 mb-7">{[
      ['Correct', data.correct, 'text-emerald-600'], ['Wrong', data.wrong, 'text-red-600'], ['Unanswered', data.unanswered, 'text-amber-600'], ['Accuracy', `${data.accuracy}%`, 'text-blue-600'], ['Avg. time', `${data.averageTime}s`, 'text-violet-600'],
    ].map(([label, value, color]) => <div key={String(label)} className="bg-white dark:bg-neutral-900 border border-slate-100 dark:border-neutral-800 rounded-2xl p-5"><p className="text-[10px] uppercase tracking-widest font-black text-slate-400">{label}</p><p className={`text-2xl font-black mt-2 ${color}`}>{value}</p></div>)}</div>
    <div className="grid lg:grid-cols-3 gap-5"><Performance title="Section performance" items={data.sectionPerformance} /><Performance title="Topic performance" items={data.topicPerformance} /><Performance title="Difficulty performance" items={data.difficultyPerformance} /></div>
    <div className="grid md:grid-cols-2 gap-5 mt-5"><div className="bg-red-50 dark:bg-red-950/20 rounded-3xl p-6"><h2 className="font-black text-red-700 dark:text-red-300">Weak topics</h2><p className="mt-3 text-sm font-semibold text-red-600 dark:text-red-400">{data.weakTopics.length ? data.weakTopics.join(', ') : 'No weak topics identified'}</p></div><div className="bg-emerald-50 dark:bg-emerald-950/20 rounded-3xl p-6"><h2 className="font-black text-emerald-700 dark:text-emerald-300">Strong topics</h2><p className="mt-3 text-sm font-semibold text-emerald-600 dark:text-emerald-400">{data.strongTopics.length ? data.strongTopics.join(', ') : 'Keep practising to build a strong topic'}</p></div></div>
    <section className="mt-8"><div className="flex items-center justify-between mb-5"><h2 className="text-2xl font-black text-slate-900 dark:text-neutral-100">Review answers</h2><Link to="/aptitude" className="text-blue-600 font-black text-sm">Take another test →</Link></div><div className="space-y-4">{data.questions.map((question, index) => <article key={question.questionId} className="bg-white dark:bg-neutral-900 border border-slate-100 dark:border-neutral-800 rounded-3xl p-6"><div className="flex justify-between gap-4"><p className="text-xs font-black text-slate-400">Question {index + 1} · {question.topic}</p><span className={`text-xs font-black px-3 py-1 rounded-full ${question.isCorrect ? 'bg-emerald-50 text-emerald-600' : question.selectedAnswer ? 'bg-red-50 text-red-600' : 'bg-amber-50 text-amber-600'}`}>{question.isCorrect ? 'Correct' : question.selectedAnswer ? 'Wrong' : 'Unanswered'}</span></div><h3 className="mt-4 font-bold text-slate-900 dark:text-neutral-100 whitespace-pre-wrap">{question.question}</h3><div className="grid sm:grid-cols-2 gap-3 mt-5"><div className="bg-slate-50 dark:bg-neutral-800 rounded-2xl p-4 text-sm"><span className="block text-[10px] uppercase tracking-widest font-black text-slate-400 mb-1">Your answer</span>{question.selectedAnswer ? `${question.selectedAnswer}. ${question.options[question.selectedAnswer as 'A' | 'B' | 'C' | 'D']}` : 'Not answered'}</div><div className="bg-emerald-50 dark:bg-emerald-950/20 rounded-2xl p-4 text-sm text-emerald-700 dark:text-emerald-300"><span className="block text-[10px] uppercase tracking-widest font-black mb-1">Correct answer</span>{question.correctAnswer}. {question.options[question.correctAnswer as 'A' | 'B' | 'C' | 'D']}</div></div><p className="text-xs text-slate-400 font-bold mt-3">Time: {question.timeTakenSeconds}s</p></article>)}</div></section>
  </main></Layout>;
};

export default AptitudeResult;
